In [5]:
import pandas as pd
import json

config    = pd.read_csv("config.csv")
absolute  = pd.read_csv("absolute.csv")
evaluator = pd.read_csv("evaluator.csv")
actor     = pd.read_csv("actor.csv")
trainer   = pd.read_csv("trainer.csv")

DEPTH_COLS = ["entropy_depth", "ess_fraction_depth", "mean_td_weights_depth", "particles_alive_depth", "resample_depth"]
for col in DEPTH_COLS:
    trainer[col] = trainer[col].apply(lambda x: json.loads(x) if pd.notna(x) and x != "" else [])

df = (
    config
    .merge(absolute,  on="exp_id", suffixes=("", "_abs"))
    .merge(evaluator, on="exp_id", suffixes=("", "_eval"))
    .merge(actor,     on="exp_id", suffixes=("", "_actor"))
    .merge(trainer,   on="exp_id", suffixes=("", "_trainer"))
)

df.shape

(20, 63)

In [6]:
df = df.fillna(0)

In [7]:
df.to_csv("analysis.csv", index=False)

In [8]:
df.columns

Index(['exp_id', 'env', 'total_num_envs', 'total_timesteps', 'num_particles',
       'search_depth', 'resampling_mode', 'ess_threshold', 'period',
       'use_residual', 'total_batch_size', 'rollout_length', 'actor_lr',
       'critic_lr', 'gamma', 'gae_lambda', 'timestep', 'steps_per_second',
       'episode_length_mean', 'episode_length_std', 'episode_length_min',
       'episode_length_max', 'episode_return_mean', 'episode_return_std',
       'episode_return_min', 'episode_return_max', 'steps_per_second_eval',
       'episode_length_mean_eval', 'episode_length_std_eval',
       'episode_length_min_eval', 'episode_length_max_eval',
       'episode_return_mean_eval', 'episode_return_std_eval',
       'episode_return_min_eval', 'episode_return_max_eval',
       'steps_per_second_actor', 'episode_length_mean_actor',
       'episode_length_std_actor', 'episode_length_min_actor',
       'episode_length_max_actor', 'episode_return_mean_actor',
       'episode_return_std_actor', 'episode_return_min_actor',
       'episode_return_max_actor', 'adaptive_temperature', 'alpha', 'kl_div',
       'kl_nonparametric', 'kl_nonparametric_relative', 'loss_alpha',
       'loss_dual', 'loss_kl_penalty', 'loss_policy', 'loss_temperature',
       'steps_per_second_trainer', 'value_loss', 'value_pred_mean',
       'value_pred_std', 'entropy_depth', 'ess_fraction_depth',
       'mean_td_weights_depth', 'particles_alive_depth', 'resample_depth'],
      dtype='object')

In [9]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df)

,exp_id,env,total_num_envs,total_timesteps,num_particles,search_depth,resampling_mode,ess_threshold,period,use_residual,total_batch_size,rollout_length,actor_lr,critic_lr,gamma,gae_lambda,timestep,steps_per_second,episode_length_mean,episode_length_std,episode_length_min,episode_length_max,episode_return_mean,episode_return_std,episode_return_min,episode_return_max,steps_per_second_eval,episode_length_mean_eval,episode_length_std_eval,episode_length_min_eval,episode_length_max_eval,episode_return_mean_eval,episode_return_std_eval,episode_return_min_eval,episode_return_max_eval,steps_per_second_actor,episode_length_mean_actor,episode_length_std_actor,episode_length_min_actor,episode_length_max_actor,episode_return_mean_actor,episode_return_std_actor,episode_return_min_actor,episode_return_max_actor,adaptive_temperature,alpha,kl_div,kl_nonparametric,kl_nonparametric_relative,loss_alpha,loss_dual,loss_kl_penalty,loss_policy,loss_temperature,steps_per_second_trainer,value_loss,value_pred_mean,value_pred_std,entropy_depth,ess_fraction_depth,mean_td_weights_depth,particles_alive_depth,resample_depth
0,1,xland_minigrid/empty_5x5,128,3000000,16,8,period,0.0,2.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,290.372,5.724,0.972,5.0,11.0,0.948,0.009,0.901,0.955,18892.318,5.641,1.006,5.0,12.0,0.949,0.009,0.892,0.955,41016.440,5.762,0.991,5,14,0.948,0.009,0.874,0.955,0.609,0.000,0.000,0.500,1.000,0.0,1.528,0.000,0.543,1.528,1281.764,0.000,0.924,0.016,"[2.773, 2.773, 2.772, 2.773, 2.772, 2.773, 2.7...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[0.008, 0.014, 0.001, 0.005, -0.0, 0.001, -0.0...","[1.0, 0.826, 0.653, 0.503, 0.359, 0.258, 0.155...","[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]"
1,2,xland_minigrid/empty_5x5,128,3000000,16,8,ess,0.5,0.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,247.985,5.002,0.039,5.0,6.0,0.955,0.000,0.946,0.955,22989.770,5.000,0.000,5.0,5.0,0.955,0.000,0.955,0.955,43462.601,5.005,0.074,5,6,0.955,0.001,0.946,0.955,0.012,0.000,0.000,0.501,1.003,0.0,0.946,0.000,0.019,0.946,1358.206,0.000,0.936,0.013,"[2.772, 2.772, 2.771, 2.771, 2.771, 2.771, 2.7...","[0.999, 0.999, 0.998, 0.998, 0.998, 0.997, 0.9...","[0.008, 0.013, 0.017, 0.019, 0.019, 0.019, 0.0...","[1.0, 0.801, 0.601, 0.402, 0.202, 0.003, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
2,3,xland_minigrid/door_key_5x5,128,3000000,16,8,ess,0.5,0.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,530.279,11.812,2.650,7.0,23.0,0.957,0.010,0.917,0.975,32493.021,12.016,2.798,7.0,19.0,0.957,0.010,0.932,0.975,43617.788,11.859,2.666,7,28,0.957,0.010,0.899,0.975,0.448,0.000,0.000,0.500,1.000,0.0,1.395,0.000,0.632,1.395,1363.056,0.000,0.903,0.034,"[2.773, 2.772, 2.772, 2.772, 2.772, 2.772, 2.7...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[0.008, 0.016, 0.023, 0.029, 0.034, 0.039, 0.0...","[1.0, 0.916, 0.832, 0.748, 0.664, 0.579, 0.495...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
3,4,xland_minigrid/door_key_5x5,128,3000000,16,8,period,0.0,2.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,523.452,11.394,2.684,7.0,22.0,0.959,0.010,0.921,0.975,26746.529,11.469,2.931,7.0,21.0,0.959,0.011,0.924,0.975,42886.719,11.273,2.693,7,25,0.959,0.010,0.910,0.975,0.529,0.000,0.000,0.500,1.000,0.0,1.361,0.000,0.489,1.361,1340.210,0.000,0.907,0.035,"[2.773, 2.773, 2.772, 2.772, 2.772, 2.772, 2.7...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[0.008, 0.016, 0.004, 0.011, 0.001, 0.007, 0.0...","[1.0, 0.912, 0.823, 0.755, 0.686, 0.604, 0.536...","[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]"
4,5,xland_minigrid/door_key_8x8,128,3000000,16,8,ess,0.5,0.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,989.832,22.341,11.145,9.0,208.0,0.969,0.016,0.707,0.987,15474.300,23.273,12.721,11.0,120.0,0.967,0.018,0.831,0.985,42470.925,22.931,17.018,7,640,0.968,0.025,0.000,0.990,0.158,0.565,0.001,0.501,1.002,0.0,0.516,0.001,0.383,0.515,1327.216,0.001,0.849,0.074,"[2.77, 2.769, 2.768, 2.767, 2.767, 2.766, 2.76...","[0.996, 0.993, 0.992, 0.99, 0.989, 0.988, 0.98...","[0.007, 0.015, 0.022, 0.029, 0.036, 0.043, 0.0...","[1.0, 0.956, 0.912, 0.869, 0.825, 0.781, 0.737...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
5,6,xland_minigrid/door_key_8x8,128,3000000,16,8,period,0.0,2.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,1136.667,26.377,20.365,9.0,327.0,0.963,0.029,0.540,0.987,10371.611,26.445,19.845,11.0,200.0,0.963,0.028,0.719,0.985,42053.212,26.202,22.947,8,640,0.963,0.033,0.000,0.989,0.215,1.756,0.001,0.501,1.001,0.0,0.469,0.002,0.455,0.469,1314.163,0.001,0.816,0.092,"[2.77, 2.769, 2.767, 2.764, 2.765, 2.762, 2.76...","[0.995, 0.993, 0.989, 0.984, 0.985, 0.98, 0.98...","[0.007, 0.014, 0.004, 0.011, 0.002, 0.009, 0.0...","[1.0, 0.963, 0.922, 0.878, 0.848, 0.803, 0.774...","[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]"
6,7,xland_minigrid/door_key_16x16,128,3000000,16,8,ess,0.5,0.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,67327.946,2559.631,13.188,2088.0,2560.0,0.000,0.007,0.000,0.266,86567.681,2560.000,0.000,2560.0,2560.0,0.000,0.000,0.000,0.000,40107.804,2560.000,0.000,2560,2560,0.000,0.000,0.000,0.000,0.000,3.062,0.001,0.498,0.997,-0.0,-0.000,0.003,1.405,0.000,1253.369,0.000,0.000,0.001,"[2.602, 2.565, 2.546, 2.536, 2.527, 2.521, 2.5...","[0.816, 0.779, 0.764, 0.753, 0.745, 0.74, 0.73...","[-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0]","[1.0, 0.999, 0.998, 0.997, 0.997, 0.996, 0.995...","[0.08, 0.102, 0.109, 0.114, 0.119, 0.122, 0.12..."
7,8,xland_minigrid/door_key_8x8,128,3000000,4,8,ess,0.5,0.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,1140.405,24.779,18.779,9.0,336.0,0.965,0.026,0.528,0.987,18418.382,23.930,13.344,12.0,121.0,0.966,0.019,0.830,0.983,45214.902,23.550,15.191,8,334,0.967,0.021,0.530,0.989,0.023,3.231,0.001,0.500,1.000,0.0,0.364,0.003,0.417,0.364,1412.966,0.001,0.844,0.071,"[1.314, 1.282, 1.263, 1.251, 1.241, 1.234, 1.2...","[0.927, 0.895, 0.876, 0.863, 0.852, 0.845, 0.8...","[0.007, 0.013, 0.018, 0.023, 0.027, 0.032, 0.0...","[1.0, 0.959, 0.919, 0.877, 0.836, 0.794, 0.753...","[0.039, 0.052, 0.06, 0.065, 0.071, 0.073, 0.07..."
8,9,xland_minigrid/door_key_8x8,128,3000000,4,8,period,0.0,2.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,18595.350,419.914,241.889,17.0,640.0,0.357,0.388,0.000,0.976,93556.304,611.969,111.246,81.0,640.0,0.046,0.180,0.000,0.886,44895.220,609.419,112.642,88,640,0.050,0.184,0.000,0.876,0.002,6.202,0.001,0.497,0.995,-0.0,0.001,0.006,0.997,0.001,1402.976,0.000,0.024,0.050,"[1.254, 1.209, 1.198, 1.162, 1.189, 1.151, 1.1...","[0.894, 0.859, 0.851, 0.825, 0.845, 0.818, 0.8...","[-0.0, -0.001, -0.001, -0.002, -0.001, -0.002,...","[1.0, 0.998, 0.997, 0.995, 0.994, 0.992, 0.99,...","[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]"
9,10,xland_minigrid/door_key_8x8,128,3000000,4,8,ess,0.8,0.0,False,64,32,0.0003,0.0003,0.99,0.95,2949120,24748.174,541.949,187.244,25.0,640.0,0.161,0.304,0.000,0.965,105756.146,640.000,0.000,640.0,640.0,0.000,0.000,0.000,0.000,45388.938,640.000,0.000,640,640,0.000,0.000,0.000,0.000,0.000,0.004,0.001,0.013,0.026,0.0,0.000,0.000,0.991,-0.000,1418.404,0.000,0.000,0.001,"[1.385, 1.384, 1.383, 1.383, 1.383, 1.384, 1.3...","[0.999, 0.998, 0.998, 0.998, 0.998, 0.998, 0.9...","[-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0]","[1.0, 0.998, 0.997, 0.995, 0.994, 0.992, 0.991...","[0.004, 0.005, 0.006, 0.006, 0.006, 0.006, 0.0..."
10,11,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.5,0.0,False,64,128,0.0003,0.0003,0.99,0.95,4997120,1452.770,194.753,333.784,23.0,2560.0,0.931,0.124,0.000,0.992,1017.030,201.469,334.276,47.0,2560.0,0.928,0.129,0.000,0.983,3507.545,212.845,358.744,26,2560,0.924,0.134,0.000,0.991,0.428,0.528,0.001,0.504,1.008,0.0,0.950,0.001,0.968,0.950,109.611,0.003,0.303,0.212,"[2.77, 2.769, 2.767, 2.766, 2.765, 2.764, 2.76...","[0.996, 0.993, 0.99, 0.988, 0.986, 0.984, 0.98...","[0.003, 0.006, 0.009, 0.012, 0.015, 0.018, 0.0...","[1.0, 0.995, 0.99, 0.985, 0.98, 0.975, 0.97, 0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
11,12,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.5,0.0,True,64,128,0.0003,0.0003,0.99,0.95,4997120,3001.793,418.827,731.450,26.0,2560.0,0.844,0.282,0.000,0.991,1676.272,405.500,723.202,41.0,2560.0,0.849,0.280,0.000,0.986,2860.946,557.954,842.793,34,2560,0.792,0.326,0.000,0.988,0.106,1.696,0.001,0.503,1.005,-0.0,0.204,0.002,1.119,0.204,89.405,0.002,0.136,0.138,"[2.756, 2.746, 2.739, 2.733, 2.728, 2.725, 2.7...","[0.975, 0.961, 0.952, 0.945, 0.939, 0.933, 0.9...","[0.001, 0.001, 0.0, 0.0, -0.0, -0.0, -0.001, -...","[1.0, 0.997, 0.995, 0.993, 0.991, 0.989, 0.987...","[0.007, 0.012, 0.014, 0.017, 0.019, 0.02, 0.02..."
12,13,xland_minigrid/door_key_16x16,32,5000000,16,64,period,0.0,4.0,False,64,128,0.0003,0.0003,0.99,0.95,4997120,16483.761,2546.738,141.423,351.0,2560.0,0.006,0.059,0.000,0.877,12196.401,2560.000,0.000,2560.0,2560.0,0.000,0.000,0.000,0.000,3497.285,2560.000,0.000,2560,2560,0.000,0.000,0.000,0.000,0.001,2.205,0.001,0.498,0.995,0.0,0.000,0.002,0.636,0.000,109.290,0.000,0.000,0.000,"[2.763, 2.759, 2.755, 2.751, 2.743, 2.739, 2.7...","[0.991, 0.986, 0.982, 0.979, 0.968, 0.964, 0.9...","[-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0....","[1.0, 1.0, 0.999, 0.999, 0.998, 0.998, 0.997, ...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
13,14,xland_minigrid/door_key_16x16,32,5000000,16,64,period,0.0,4.0,True,64,128,0.0003,0.0003,0.99,0.95,4997120,16907.118,2393.766,558.554,45.0,2560.0,0.067,0.224,0.000,0.984,10561.869,2414.781,563.731,45.0,2560.0,0.057,0.222,0.000,0.984,3233.853,2381.037,607.297,59,2560,0.071,0.241,0.000,0.979,0.003,1.759,0.001,0.502,1.005,0.0,-0.000,0.002,0.732,-0.000,101.058,0.000,0.003,0.016,"[2.756, 2.74, 2.731, 2.728, 2.73, 2.718, 2.716...","[0.985, 0.975, 0.969, 0.967, 0.966, 0.957, 0.9...","[0.0, 0.0, 0.0, 0.0, -0.001, -0.001, -0.001, -...","[1.0, 1.0, 0.999, 0.999, 0.998, 0.998, 0.997, ...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
14,15,xland_minigrid/door_key_16x16,32,5000000,32,64,period,0.0,4.0,True,64,128,0.0003,0.0003,0.99,0.95,4997120,17822.572,2555.256,85.956,728.0,2560.0,0.002,0.036,0.000,0.744,9625.898,2545.734,160.765,734.0,2560.0,0.006,0.065,0.000,0.742,2834.603,2560.000,0.000,2560,2560,0.000,0.000,0.000,0.000,0.001,1.152,0.001,0.495,0.990,0.0,-0.000,0.001,0.916,-0.000,88.581,0.000,0.000,0.001,"[3.446, 3.437, 3.431, 3.427, 3.426, 3.416, 3.4...","[0.987, 0.981, 0.977, 0.974, 0.969, 0.964, 0.9...","[0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0...","[1.0, 1.0, 0.999, 0.999, 0.998, 0.998, 0.997, ...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
15,16,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.3,0.0,True,64,128,0.0003,0.0003,0.99,0.95,4997120,823.128,123.834,161.749,18.0,2560.0,0.956,0.059,0.000,0.994,551.863,139.391,257.733,27.0,2478.0,0.951,0.091,0.129,0.991,2667.711,130.186,191.636,25,2560,0.954,0.069,0.000,0.991,0.392,0.384,0.001,0.499,0.998,0.0,0.845,0.000,0.920,0.845,83.366,0.003,0.465,0.195,"[2.77, 2.768, 2.767, 2.766, 2.764, 2.763, 2.76...","[0.995, 0.992, 0.989, 0.987, 0.985, 0.983, 0.9...","[0.004, 0.008, 0.013, 0.017, 0.021, 0.025, 0.0...","[1.0, 0.992, 0.984, 0.977, 0.969, 0.961, 0.953...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
16,17,xland_minigrid/door_key_16x16,32,5000000,16,64,period,0.0,65.0,True,64,128,0.0003,0.0003,0.99,0.95,4997120,1460.158,195.720,343.729,20.0,2560.0,0.930,0.127,0.000,0.993,1136.075,238.766,420.914,22.0,2560.0,0.914,0.157,0.000,0.992,3528.633,186.708,330.668,23,2560,0.934,0.122,0.000,0.992,0.605,0.341,0.001,0.500,1.001,0.0,1.423,0.000,1.042,1.423,110.270,0.005,0.337,0.175,"[2.771, 2.769, 2.768, 2.768, 2.767, 2.766, 2.7...","[0.996, 0.994, 0.992, 0.99, 0.989, 0.988, 0.98...","[0.003, 0.007, 0.01, 0.013, 0.016, 0.019, 0.02...","[1.0, 0.995, 0.989, 0.984, 0.979, 0.973, 0.968...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
17,18,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.3,0.0,False,64,128,0.0003,0.0003,0.99,0.95,4997120,1114.637,146.041,245.619,23.0,2560.0,0.948,0.093,0.000,0.992,1154.077,142.555,186.707,36.0,1627.0,0.950,0.066,0.428,0.987,3558.427,159.651,259.830,26,2560,0.943,0.097,0.000,0.991,0.400,0.582,0.001,0.500,1.000,0.0,0.892,0.001,0.928,0.892,111.201,0.003,0.397,0.199,"[2.77, 2.768, 2.767, 2.765, 2.764, 2.763, 2.76...","[0.995, 0.992, 0.989, 0.986, 0.984, 0.982, 0.9...","[0.004, 0.007, 0.011, 0.014, 0.018, 0.021, 0.0...","[1.0, 0.994, 0.987, 0.981, 0.975, 0.968, 0.962...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
18,19,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.7,0.0,False,64,128,0.0003,0.0003,0.99,0.95,4997120,2779.633,366.418,606.002,25.0,2560.0,0.866,0.231,0.000,0.991,2267.627,441.125,771.373,39.0,2560.0,0.835,0.299,0.000,0.986,3543.360,351.252,582.941,27,2560,0.872,0.221,0.000,0.991,0.194,1.549,0.001,0.504,1.008,0.0,0.435,0.001,0.963,0.435,110.730,0.003,0.199,0.171,"[2.768, 2.763, 2.76, 2.757, 2.755, 2.753, 2.75...","[0.991, 0.984, 0.979, 0.975, 0.971, 0.968, 0.9...","[0.002, 0.003, 0.004, 0.005, 0.005, 0.006, 0.0...","[1.0, 0.997, 0.994, 0.991, 0.989, 0.986, 0.983...","[0.003, 0.007, 0.01, 0.013, 0.015, 0.017, 0.01..."
19,20,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.7,0.0,True,64,128,0.0003,0.0003,0.99,0.95,4997120,1707.700,235.537,444.222,23.0,2560.0,0.914,0.171,0.000,0.992,1120.486,267.125,544.165,32.0,2560.0,0.901,0.211,0.000,0.989,2918.369,257.995,444.754,30,2560,0.907,0.169,0.000,0.989,0.309,0.926,0.001,0.501,1.001,-0.0,0.720,0.001,0.973,0.720,91.199,0.003,0.272,0.194,"[2.769, 2.767, 2.765, 2.764, 2.762, 2.761, 2.7...","[0.994, 0.99, 0.987, 0.984, 0.981, 0.979, 0.97...","[0.003, 0.005, 0.007, 0.009, 0.01, 0.012, 0.01...","[1.0, 0.996, 0.992, 0.988, 0.984, 0.981, 0.977...","[0.001, 0.003, 0.004, 0.005, 0.007, 0.008, 0.0..."

In [10]:
df[
    (df["env"] == "xland_minigrid/door_key_16x16") &
    (df["total_num_envs"] == 32)
]

,exp_id,env,total_num_envs,total_timesteps,num_particles,search_depth,resampling_mode,ess_threshold,period,use_residual,...,loss_temperature,steps_per_second_trainer,value_loss,value_pred_mean,value_pred_std,entropy_depth,ess_fraction_depth,mean_td_weights_depth,particles_alive_depth,resample_depth
10,11,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.5,0.0,False,...,0.950,109.611,0.003,0.303,0.212,"[2.77, 2.769, 2.767, 2.766, 2.765, 2.764, 2.76...","[0.996, 0.993, 0.99, 0.988, 0.986, 0.984, 0.98...","[0.003, 0.006, 0.009, 0.012, 0.015, 0.018, 0.0...","[1.0, 0.995, 0.99, 0.985, 0.98, 0.975, 0.97, 0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
11,12,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.5,0.0,True,...,0.204,89.405,0.002,0.136,0.138,"[2.756, 2.746, 2.739, 2.733, 2.728, 2.725, 2.7...","[0.975, 0.961, 0.952, 0.945, 0.939, 0.933, 0.9...","[0.001, 0.001, 0.0, 0.0, -0.0, -0.0, -0.001, -...","[1.0, 0.997, 0.995, 0.993, 0.991, 0.989, 0.987...","[0.007, 0.012, 0.014, 0.017, 0.019, 0.02, 0.02..."
12,13,xland_minigrid/door_key_16x16,32,5000000,16,64,period,0.0,4.0,False,...,0.000,109.290,0.000,0.000,0.000,"[2.763, 2.759, 2.755, 2.751, 2.743, 2.739, 2.7...","[0.991, 0.986, 0.982, 0.979, 0.968, 0.964, 0.9...","[-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0....","[1.0, 1.0, 0.999, 0.999, 0.998, 0.998, 0.997, ...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
13,14,xland_minigrid/door_key_16x16,32,5000000,16,64,period,0.0,4.0,True,...,-0.000,101.058,0.000,0.003,0.016,"[2.756, 2.74, 2.731, 2.728, 2.73, 2.718, 2.716...","[0.985, 0.975, 0.969, 0.967, 0.966, 0.957, 0.9...","[0.0, 0.0, 0.0, 0.0, -0.001, -0.001, -0.001, -...","[1.0, 1.0, 0.999, 0.999, 0.998, 0.998, 0.997, ...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
14,15,xland_minigrid/door_key_16x16,32,5000000,32,64,period,0.0,4.0,True,...,-0.000,88.581,0.000,0.000,0.001,"[3.446, 3.437, 3.431, 3.427, 3.426, 3.416, 3.4...","[0.987, 0.981, 0.977, 0.974, 0.969, 0.964, 0.9...","[0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0...","[1.0, 1.0, 0.999, 0.999, 0.998, 0.998, 0.997, ...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, ..."
15,16,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.3,0.0,True,...,0.845,83.366,0.003,0.465,0.195,"[2.77, 2.768, 2.767, 2.766, 2.764, 2.763, 2.76...","[0.995, 0.992, 0.989, 0.987, 0.985, 0.983, 0.9...","[0.004, 0.008, 0.013, 0.017, 0.021, 0.025, 0.0...","[1.0, 0.992, 0.984, 0.977, 0.969, 0.961, 0.953...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
16,17,xland_minigrid/door_key_16x16,32,5000000,16,64,period,0.0,65.0,True,...,1.423,110.270,0.005,0.337,0.175,"[2.771, 2.769, 2.768, 2.768, 2.767, 2.766, 2.7...","[0.996, 0.994, 0.992, 0.99, 0.989, 0.988, 0.98...","[0.003, 0.007, 0.01, 0.013, 0.016, 0.019, 0.02...","[1.0, 0.995, 0.989, 0.984, 0.979, 0.973, 0.968...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
17,18,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.3,0.0,False,...,0.892,111.201,0.003,0.397,0.199,"[2.77, 2.768, 2.767, 2.765, 2.764, 2.763, 2.76...","[0.995, 0.992, 0.989, 0.986, 0.984, 0.982, 0.9...","[0.004, 0.007, 0.011, 0.014, 0.018, 0.021, 0.0...","[1.0, 0.994, 0.987, 0.981, 0.975, 0.968, 0.962...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
18,19,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.7,0.0,False,...,0.435,110.730,0.003,0.199,0.171,"[2.768, 2.763, 2.76, 2.757, 2.755, 2.753, 2.75...","[0.991, 0.984, 0.979, 0.975, 0.971, 0.968, 0.9...","[0.002, 0.003, 0.004, 0.005, 0.005, 0.006, 0.0...","[1.0, 0.997, 0.994, 0.991, 0.989, 0.986, 0.983...","[0.003, 0.007, 0.01, 0.013, 0.015, 0.017, 0.01..."
19,20,xland_minigrid/door_key_16x16,32,5000000,16,64,ess,0.7,0.0,True,...,0.720,91.199,0.003,0.272,0.194,"[2.769, 2.767, 2.765, 2.764, 2.762, 2.761, 2.7...","[0.994, 0.99, 0.987, 0.984, 0.981, 0.979, 0.97...","[0.003, 0.005, 0.007, 0.009, 0.01, 0.012, 0.01...","[1.0, 0.996, 0.992, 0.988, 0.984, 0.981, 0.977...","[0.001, 0.003, 0.004, 0.005, 0.007, 0.008, 0.0..."